name: 'Bookshelf'
author: 'Joris Guffens'
version: ${pluginVersion}
api-version: 1.18
description: 'The complete library for building minecraft plugins quickly and efficient'
main: com.gufli.bookshelf.bukkit.BukkitShelf
softdepend: [ProtocolLib]
commands:
  bookshelf:
    description: "for debugging only"
    aliases: [bs]